version: '3.8'

services:
  penalty-bot:
    build: .
    container_name: penalty_calculator_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - SHEET_NAME=${SHEET_NAME}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 